# Generated by Django 5.1.1 on 2025-09-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productimage_is_main_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
